### ISSUE TITLE
Client ID Invalid

### ISSUE THREAD

**Issue by stevo2105** [shyambhat/InstagramKit#72]
This is becoming a problem. My Client ID is in fact valid, and I have filled in every spot in the Kit where it asks for Client ID. Thanks!!!!!!!!!!!!!!!!!!! Any help would be GREATLY appreciated.

**Comment by garyjohnson** [comment]
Not sure if you're seeing the same thing we were, but we had a similar error. This would not occur the on the first run of the app, but subsequent build+runs would cause this to occur. It looks like the InstagramKit.plist was overriding our local one, even though the 'Copy Pods Resources' build phase is set to occur before the 'Copy Bundle Resources' phase. Doing an option+clean (Clean Build Folder...) would allow this to run once more before failing again.

Oddly, this also did not occur on all machines but did occur for any new devs that pulled down the project.

Our solution was to fork the repo, and from the podspec file delete the s.resources line and add the plist to the s.exclude_files so that it looks like this:
```
  s.exclude_files = 'InstagramKitDemo',
                             'InstagramKit/InstragramKit.plist'
```

Without understanding why the file is getting overwritten by the one in the pod, this seems like a workaround more than a solution.

**Comment by shyambhat** [comment]
This issue is fixed in v3.6.4.

**Comment by abury** [comment]
I'm still getting this issue in 3.6.5. I'm using Swift 2.0 so i'm not sure if that has any impact.
Do you know what's causing the original issue?

**Comment by abury** [comment]
Just read a bit more into this, it looks like a change in cocoapods. If using frameworks, NSBundle.bundleForClass references the bundle being bought in by the pod, whereas mainBundle references the main application bundle.
Given we're asked to put the instagramID and redirectURL into our main bundle's info.plist, should line 70 of InstagramEngine not use 
```[NSBundle mainBundle] ```
instead of 
```[NSBundle bundleForClass:[self class]]```

I suspect this only affects people who are using cocoapods and the use_frameworks! option, but this will become more of a norm as the months go on.

**Comment by shyambhat** [comment]
Thanks @abury for the catch. `[NSBundle mainBundle]` is the way to go. Will get this fixed as soon as I finish my day at work. :)
